KNUT-Hackathon/Networker

- src/css/board.css
- views/board.html
- views/emailchange.html
- views/inquire.html
- 게시판 페이지 css 수정 및 주석 추가
- pull request 테스트
> 게시판 페이지 css 수정 및 주석 추가

- src/css/board.css
- src/css/emailchange.css
- src/css/inquire.css
- src/css/login.css
- src/css/nicknamesetting.css
- src/css/passwordchange.css
- src/css/post.css
- src/css/profile.css
- src/css/signup.css
- src/css/write.css
- views/board.html
- views/emailchange.html
- views/inquire.html
- views/login.html
- views/nicknamesetting.html
- views/passwordchange.html
- views/post.html
- views/profile.html
- views/signup.html
- views/verify.html
- views/write.html
- 파일 구조의 변화에 따라 html의 a 태그를 통한 이동 경로를 전부 수정(html)
- 헤더, 푸터 코드 추가(html, css)
- 새로운 테마 컬러에 맞추어 헤더 스타일 수정(css)
> href 이동경로 수정, 헤더/푸터 추가 및 스타일 수정

- src/main/resources/static/src/js/deleteaccount.js
- src/main/resources/static/views/deleteaccount.html
[ProntEnd]
회원탈퇴 기능 구현을 위한 js 코드 업데이트
> #14 회원탈퇴 js 코드

- src/main/resources/static/src/css/deleteaccount.css
- src/main/resources/static/src/css/emailchange.css
- src/main/resources/static/src/css/login.css
- src/main/resources/static/src/css/nicknamesetting.css
- src/main/resources/static/src/css/passwordchange.css
- src/main/resources/static/src/css/profile.css
- src/main/resources/static/src/css/signup.css
- src/main/resources/static/src/js/board.js
- src/main/resources/static/src/js/login.js
- src/main/resources/static/src/js/profile.js
- src/main/resources/static/views/deleteaccount.html
- src/main/resources/static/views/emailchange.html
- src/main/resources/static/views/login.html
- src/main/resources/static/views/nicknamesetting.html
- src/main/resources/static/views/passwordchange.html
- src/main/resources/static/views/profile.html
- src/main/resources/static/views/signup.html
> #17, #18 헤더 아이콘 조정, 프로필 정보 확인, 로그아웃 js 코드 개발

- src/main/resources/static/src/css/board.css
- src/main/resources/static/src/js/board.js
- src/main/resources/static/src/js/deleteaccount.js
> 로그인 여부에 따른 헤더 변경, 회원탈퇴 js 코드 수정

- src/main/java/com/example/networker_test/controller/user/UserController.java
- src/main/java/com/example/networker_test/service/user/UserService.java
- src/main/resources/static/src/js/board.js
> #29 로그인 여부에 따른 헤더 요소 변경

- src/main/java/com/example/networker_test/controller/user/UserController.java
- src/main/java/com/example/networker_test/domain/user/User.java
- src/main/java/com/example/networker_test/domain/user/UserRepository.java
- src/main/java/com/example/networker_test/dto/user/reponese/UserResponse.java
- src/main/java/com/example/networker_test/dto/user/request/UserCreateRequest.java
- src/main/java/com/example/networker_test/service/user/UserService.java
유저정보에 닉네임 추가 (user 테이블 수정), 회원탈퇴시 비밀번호 일치시 탈퇴하도록 변경 (프론트엔드 코드는 아직 안 고침)
> #32 #21 닉네임 추가 및 회원탈퇴 기능 수정

- src/main/resources/static/src/css/post.css
- src/main/resources/static/src/css/signup.css
- src/main/resources/static/src/css/write.css
- src/main/resources/static/src/js/inquire.js
- src/main/resources/static/src/js/lawsupport.js
- src/main/resources/static/src/js/networker.js
- src/main/resources/static/src/js/news.js
- src/main/resources/static/src/js/post.js
- src/main/resources/static/src/js/profile.js
- src/main/resources/static/views/networker.html
- src/main/resources/static/views/news.html
- src/main/resources/static/views/profile.html
- src/main/resources/static/views/signup.html
- src/main/resources/static/views/write.html
- 회원가입 시 닉네임을 입력받도록 html, js코드 수정
- 로그인 여부에 따른 헤더 요소 변경 기능이 필요한 모든 페이지에 코드 추가.
> 회원가입 입력 정보 추가, 로그인 여부에 따른 헤더 요소 변경 기능 

- src/main/resources/static/src/js/deleteaccount.js
- src/main/resources/static/src/js/emailchange.js
- src/main/resources/static/src/js/nicknamesetting.js
- src/main/resources/static/src/js/passwordchange.js
이슈 번호 #14, #37 참고
- 회원 탈퇴 js 코드의 일부분이 제대로 동작하지 않고 있는 이슈를 해결하기 위해 코드 수정
- 회원 정보 변경 기능을 구현하기 위해, 웹서버에 변경 요청을 하고, 응답에 따라 적절한 행동을 수행하는 js 코드 개발
> 회원 탈퇴, 회원 정보 변경 기능 관련 프론트엔드 개발 내용 업데이트

- src/main/java/com/example/networker_test/controller/user/UserController.java
- src/main/java/com/example/networker_test/domain/user/User.java
- src/main/java/com/example/networker_test/service/user/UserService.java
- src/main/resources/static/src/js/deleteaccount.js
- src/main/resources/static/src/js/emailchange.js
- src/main/resources/static/src/js/nicknamesetting.js
- src/main/resources/static/src/js/passwordchange.js
- src/main/resources/static/src/js/signup.js
> #37 비번,이메일,닉넴 변경 백엔드 코드 구현

- src/main/resources/static/src/css/signup.css
- src/main/resources/static/src/js/deleteaccount.js
- src/main/resources/static/src/js/profile.js
- src/main/resources/static/src/js/signup.js
- src/main/resources/static/views/profile.html
- src/main/resources/static/views/signup.html
- 이슈 #41 참고
- 프로필 페이지의 아이디 확인용 메뉴 요소를 제거(로그아웃 버튼 위에서 아이디 확인 가능)
> 회원가입 시 비밀번호 유효성 검사, 프로필 메뉴 수정

- src/main/resources/static/src/css/createpost.css
- src/main/resources/static/src/css/lawsupport.css
- src/main/resources/static/src/js/createpost.js
- src/main/resources/static/src/js/lawsupport.js
- src/main/resources/static/views/createpost.html
- src/main/resources/static/views/lawsupport.html
게시글 작성 페이지 #40
법률지원 id태그 작성 #43
하나의 커밋은 원격저장소에서 fetch한 내용과 로컬 레포지토리 merge한 내용입니다.
> #43 #40 작업

- build.gradle
- src/main/java/com/example/networker_test/DataNotFoundException.java
- src/main/java/com/example/networker_test/MainController.java
- src/main/java/com/example/networker_test/comment/Comment.java
- src/main/java/com/example/networker_test/comment/CommentController.java
- src/main/java/com/example/networker_test/comment/CommentRepository.java
- src/main/java/com/example/networker_test/comment/CommentService.java
- src/main/java/com/example/networker_test/post/Post.java
- src/main/java/com/example/networker_test/post/PostController.java
- src/main/java/com/example/networker_test/post/PostRepository.java
- src/main/java/com/example/networker_test/post/PostService.java
- src/main/resources/application.yml
게시판 게시물 패키지(Post), 댓글 패키지(Comment) 추가함.
게시판과 댓글 각각 컨트롤러 패키지별로 생성함
DataNotFoundException.java 추가함
MainController.java 추가함
application.yml파일에 thymeleaf 추가함
commit 크기가 큰 점 죄송합니다ㅠㅠ
> #61 게시판, 댓글 패키지 일괄 생성

- src/main/resources/static/src/css/network.css
- src/main/resources/static/src/css/news.css
- src/main/resources/static/src/js/fetchNewsTitles.js
- src/main/resources/static/src/js/news.js
- src/main/resources/static/views/board.html
- src/main/resources/static/views/cart.html
- src/main/resources/static/views/createpost.html
- src/main/resources/static/views/deleteaccount.html
- src/main/resources/static/views/emailchange.html
- src/main/resources/static/views/inquire.html
- src/main/resources/static/views/lawsupport.html
- src/main/resources/static/views/networker.html
- src/main/resources/static/views/news.html
- src/main/resources/static/views/nicknamesetting.html
- src/main/resources/static/views/passwordchange.html
- src/main/resources/static/views/post.html
- src/main/resources/static/views/store.html
정보 게시판 간격 수정, 홈 화면 정보 게시판 제목 불러오는 기능 추가했습니다 추가로 개인정보처리방침 링크 연결도 완료했습니다
> #63 홈 화면 정보 게시판 제목 불러오기

- src/main/java/com/example/networker_test/controller/comment/CommentController.java
- src/main/java/com/example/networker_test/controller/main/MainController.java
- src/main/java/com/example/networker_test/controller/post/PostController.java
- src/main/java/com/example/networker_test/controller/store/ProductController.java
- src/main/java/com/example/networker_test/domain/comment/Comment.java
- src/main/java/com/example/networker_test/domain/post/Post.java
- src/main/java/com/example/networker_test/domain/sotre/Product.java
- src/main/java/com/example/networker_test/exception/DataNotFoundException.java
- src/main/java/com/example/networker_test/repository/comment/CommentRepository.java
- src/main/java/com/example/networker_test/repository/post/PostRepository.java
- src/main/java/com/example/networker_test/repository/store/ProductRepository.java
- src/main/java/com/example/networker_test/repository/user/UserRepository.java
- src/main/java/com/example/networker_test/service/comment/CommentService.java
- src/main/java/com/example/networker_test/service/post/PostService.java
- src/main/java/com/example/networker_test/service/store/ProductService.java
- src/main/java/com/example/networker_test/service/user/UserService.java
- src/main/resources/application.yml
- src/main/resources/static/src/js/store.js
테이블 구성
product
(
id          bigint,
price       bigint,
name        varchar(255),
image       varchar(255),
primary key (id)
);
> #65 스토어 DB연결 및 백엔드 패키지 정리

- src/main/resources/static/src/js/inquire.js
- src/main/resources/static/views/inquire.html
> #51 문의 시 첨부파일 추가

- src/main/java/com/example/networker_test/controller/inquiry/InquiryController.java
- src/main/java/com/example/networker_test/dto/inquiry/request/InquiryRequest.java
- src/main/java/com/example/networker_test/service/inquiry/InquiryService.java
- src/main/resources/application.yml
- src/main/resources/static/src/js/inquire.js
- src/main/resources/static/views/inquire.html
> #60 문의하기(백엔드)

- src/main/resources/static/src/js/order.js
- src/main/resources/static/views/order.html
> #69 오타수정, 결제 후 장바구니 데이터 삭제

- src/main/resources/static/src/js/order.js
- #69
- 결제 금액 정보가 나오지 않는 오류 수정
- DB 저장할 데이터에 유저 이메일(아이디) 정보 추가
> #69 결제 금액 출력 오류 수정

- build.gradle
- src/main/java/com/example/networker_test/controller/user/UserController.java
- src/main/java/com/example/networker_test/domain/user/User.java
- src/main/java/com/example/networker_test/service/user/UserService.java
db에 비밀번호가 그대로 보이는게 법으로 안 된다길래 해시화헀습니다
> #76 비밀번호 해시화

- build.gradle
- src/main/java/com/example/networker_test/controller/lawsupport/LawSupportController.java
- src/main/java/com/example/networker_test/controller/main/MainController.java
- src/main/resources/application.yml
- src/main/resources/static/views/profile.html
- 법률지원 컨트롤러 생성
- gradle,yml편집
- 로그인 세션 유지 테스트를 위한 profile.html 극히 일부 수정
> #84 1차 분할 커밋

- src/main/resources/static/src/css/order.css
- src/main/resources/static/src/css/payments.css
- src/main/resources/static/src/js/order.js
- src/main/resources/static/views/fail.html
- src/main/resources/static/views/order.html
- src/main/resources/static/views/success.html
- src/main/resources/static/views/test.html
- #69 
- 토스 결제 모듈 연결 구현 중, 백엔드 작업을 위해 pr했습니다.
> #69 토스 결제 모듈 연결(프론트)

- build.gradle
- src/main/java/com/example/networker_test/controller/post/PostController.java
- src/main/java/com/example/networker_test/repository/post/PostRepository.java
- src/main/java/com/example/networker_test/service/post/PostService.java
- src/main/resources/static/src/js/createpost.js
- src/main/resources/static/views/board.html
- src/main/resources/static/views/createpost.html
- src/main/resources/static/views/networker.html
- src/main/resources/static/views/post.html
> #91 자유게시판 구현 및 로그인 세션 오류 해결

- src/main/resources/static/src/css/orderinfo.css
- src/main/resources/static/src/js/orderinfo.js
- src/main/resources/static/views/orderinfo.html
- src/main/resources/static/views/profile.html
> #98 주문/결제 내역

- src/main/resources/static/src/css/productdetail.css
- src/main/resources/static/src/css/store.css
- src/main/resources/static/src/js/productdetail.js
- src/main/resources/static/src/js/store.js
- src/main/resources/static/views/productdetail.html
- #100 
- 상품 상세 페이지 개발, 스토어 아이콘 디자인 변경
- 자세한 내용은 이슈 참고
> #100 상품 상세페이지

- src/main/resources/static/src/js/createpost.js
- src/main/resources/static/views/createpost_law.html
> #117 자유게시판 글쓰기 오류 수정

- src/main/resources/static/src/js/board.js
- src/main/resources/static/src/js/cart.js
- src/main/resources/static/src/js/createpost.js
- src/main/resources/static/src/js/createpost_law.js
- src/main/resources/static/src/js/inquire.js
- src/main/resources/static/src/js/lawsupport.js
- src/main/resources/static/src/js/login.js
- src/main/resources/static/src/js/networker.js
- src/main/resources/static/src/js/news.js
- src/main/resources/static/src/js/post.js
- src/main/resources/static/src/js/post_law.js
- src/main/resources/static/src/js/store.js
- src/main/resources/static/views/emailchange.html
- src/main/resources/static/views/nicknamesetting.html
- src/main/resources/static/views/order.html
- src/main/resources/static/views/orderinfo.html
- src/main/resources/static/views/passwordchange.html
- #29 
- 개발이 진행되며 DOM 구조의 변화 등의 이유로 헤더 요소가 기존 querySelector를 통해 접근이 되지 않아 오류가 발생함.
- 아이디/비밀번호/아이콘의 id 및 class요소를 통해 접근하도록 수정함
- 프로필, 계정 설정, 결제 페이지의 경우 로그인/회원가입이 필요없기 때문에 요소 자체를 html파일에서 제거함.
- 기업리뷰 페이지는 js 코드 개발이 어느정도 완성된 후 수정할 예정
> 로그인 여부에 따른 헤더 요소 변경 오류 해결

- src/main/resources/static/src/js/company.js
- src/main/resources/static/src/js/star.js
- src/main/resources/static/views/company.html
- src/main/resources/static/views/news.html
- src/main/resources/static/views/review.html
- src/main/resources/static/views/write_review.html
기업리뷰 첫번째 회사에만 js 코드 적용해보았습니다 코드 정상 작동할 나머지는 복사 붙여넣기 하면 될거 같습니다
>  #118 기업 리뷰 js 파일 추가

- src/main/java/com/example/networker_test/controller/order/OrderController.java
- src/main/java/com/example/networker_test/domain/order/CartItems.java
- src/main/java/com/example/networker_test/domain/order/OrderInfo.java
- src/main/java/com/example/networker_test/domain/order/PaymentInfo.java
- src/main/java/com/example/networker_test/domain/order/ShippingInfo.java
- src/main/java/com/example/networker_test/dto/order/cartItem/CartItemsDTO.java
- src/main/java/com/example/networker_test/dto/order/orderinfo/OrderInfoDTO.java
- src/main/java/com/example/networker_test/dto/order/paymentinfo/PaymentInfoDTO.java
- src/main/java/com/example/networker_test/dto/order/request/OrderRequest.java
- src/main/java/com/example/networker_test/dto/order/shippinginfo/ShippingInfoDTO.java
- src/main/java/com/example/networker_test/repository/order/CartItemsRepository.java
- src/main/java/com/example/networker_test/repository/order/OrderInfoRepository.java
- src/main/java/com/example/networker_test/repository/order/PaymentInfoRepository.java
- src/main/java/com/example/networker_test/repository/order/ShippingInfoRepository.java
- src/main/java/com/example/networker_test/service/order/OrderService.java
- src/main/resources/static/src/js/order.js
> #98 주문,결제페이지

- .gitignore
- src/main/resources/static/src/css/network.css
- src/main/resources/static/src/js/checkout.js
- src/main/resources/static/views/checkout.html
- src/main/resources/static/views/profile.html
- #124
- #29 결제 페이지의 헤더 요소 수정
- #69 결제모듈 전달용으로 웹서버에 요청하는 데이터 종류 수정
> #124 #29 #69

- src/main/java/com/example/networker_test/controller/comment/CommentController.java
- src/main/java/com/example/networker_test/controller/post/PostController.java
- src/main/java/com/example/networker_test/domain/comment/Comment.java
- src/main/java/com/example/networker_test/domain/post/Post.java
- src/main/java/com/example/networker_test/service/comment/CommentService.java
- src/main/java/com/example/networker_test/service/post/PostService.java
- src/main/resources/application.yml
- src/main/resources/static/src/js/createpost.js
- src/main/resources/static/views/board.html
- src/main/resources/static/views/post.html
> #127 자유게시판 게시물/댓글 작성자 등록

- src/main/resources/static/src/css/board.css
- src/main/resources/static/src/css/cart.css
- src/main/resources/static/src/css/createpost.css
- src/main/resources/static/src/css/inquire.css
- src/main/resources/static/src/css/lawsupport.css
- src/main/resources/static/src/css/login.css
- src/main/resources/static/src/css/network.css
- src/main/resources/static/src/css/news.css
- src/main/resources/static/src/css/orderinfo.css
- src/main/resources/static/src/css/post.css
- src/main/resources/static/src/css/productdetail.css
- src/main/resources/static/src/css/profile.css
- src/main/resources/static/src/css/review.css
- src/main/resources/static/src/css/review_page.css
- src/main/resources/static/src/css/shared.css
- src/main/resources/static/src/css/signup.css
- src/main/resources/static/src/css/store.css
- src/main/resources/static/src/js/checkout.js
- src/main/resources/static/src/js/deleteaccount.js
- src/main/resources/static/src/js/emailchange.js
- src/main/resources/static/src/js/nicknamesetting.js
- src/main/resources/static/src/js/order.js
- src/main/resources/static/src/js/orderinfo.js
- src/main/resources/static/src/js/passwordchange.js
- src/main/resources/static/src/js/productdetail.js
- src/main/resources/static/src/js/profile.js
- src/main/resources/static/views/networker.html
- #29 스토어 상품 상세페이지 적용
- #130
- #131
> #29 #130 #131

- src/main/resources/static/src/js/post.js
- #107
- 필요 이상으로 복잡한 코드를 단순화 함.
- 백엔드에서 post 컨텐츠 로드할 때 user email id가 보이도록 개발하면 정상적으로 작동될 예정
> #107 게시글 수정/삭제 버튼 노출 유무 JS코드 수정

- src/main/resources/static/src/js/checkout.js
- src/main/resources/static/src/js/orderinfo.js
- src/main/resources/static/views/checkout.html
- src/main/resources/static/views/success.html
> #145 코드 일부 수정

- src/main/java/com/example/networker_test/controller/comment/CommentController.java
- src/main/java/com/example/networker_test/controller/post/PostController.java
- src/main/java/com/example/networker_test/domain/comment/Comment.java
- src/main/java/com/example/networker_test/domain/comment/CommentForm.java
- src/main/java/com/example/networker_test/domain/post/Post.java
- src/main/java/com/example/networker_test/domain/post/PostForm.java
- src/main/java/com/example/networker_test/domain/post/PostRecommendation.java
- src/main/java/com/example/networker_test/repository/post/PostRecommendationRepository.java
- src/main/java/com/example/networker_test/repository/post/PostRepository.java
- src/main/java/com/example/networker_test/service/post/PostRecommendationService.java
- src/main/java/com/example/networker_test/service/post/PostService.java
- src/main/resources/application.yml
- src/main/resources/static/views/modifypost.html
- src/main/resources/static/views/post.html
- src/main/resources/static/views/signup.html
자유게시판 수정/삭제/추천기능 구현 1
-구현 자체는 되었지만, 현재로서는 버튼이 보이지 않습니다.
다만, 수정의 경우에는 해당 게시물 주소에서 detail을 mocify로 바꾸시면 접근 가능합니다.(본인이 작성한 것만 수정 가능)
> #149 수정/삭제/추천기능 구현 1

- src/main/java/com/example/networker_test/service/post/PostService.java
- src/main/resources/application.yml
> #151 db 설정 오류 수정

- src/main/resources/static/views/board.html
- src/main/resources/static/views/cart.html
- src/main/resources/static/views/checkout.html
- src/main/resources/static/views/company.html
- src/main/resources/static/views/createpost.html
- src/main/resources/static/views/createpost_law.html
- src/main/resources/static/views/deleteaccount.html
- src/main/resources/static/views/emailchange.html
- src/main/resources/static/views/inquire.html
- src/main/resources/static/views/lawsupport.html
- src/main/resources/static/views/login.html
- src/main/resources/static/views/modifypost.html
- src/main/resources/static/views/networker.html
- src/main/resources/static/views/news.html
- src/main/resources/static/views/nicknamesetting.html
- src/main/resources/static/views/order.html
- src/main/resources/static/views/orderinfo.html
- src/main/resources/static/views/passwordchange.html
- src/main/resources/static/views/post.html
- src/main/resources/static/views/post_law.html
- src/main/resources/static/views/productdetail.html
- src/main/resources/static/views/profile.html
- src/main/resources/static/views/review.html
- src/main/resources/static/views/signup.html
- src/main/resources/static/views/store.html
- src/main/resources/static/views/write_review.html
> #158 footer 문의/신고, 광고안내 링크 연결

- src/main/java/com/example/networker_test/controller/order/OrderController.java
- src/main/java/com/example/networker_test/dto/order/orderinfo/UserOrderInfoDTO.java
- src/main/java/com/example/networker_test/repository/order/CartItemsRepository.java
- src/main/java/com/example/networker_test/repository/order/OrderInfoRepository.java
- src/main/java/com/example/networker_test/service/order/OrderService.java
- src/main/resources/static/views/orderinfo.html
테스트 결제하고 주문/결제 내역 확인 테스트 부탁드립니다
> #160 주문/결제 내역 백엔드

- src/main/java/com/example/networker_test/controller/order/OrderController.java
- src/main/resources/static/src/js/orderinfo.js
1차 테스트에서 에러 발생.
Authentication 객체를 사용하지 않고, 프론트에서 useremail을 담아 post 요청을 보내는 방식으로 수정함
> #160 에러 해결 시도

- src/main/java/com/example/networker_test/controller/order/OrderController.java
- src/main/java/com/example/networker_test/controller/store/ProductController.java
- src/main/java/com/example/networker_test/controller/user/UserController.java
- src/main/java/com/example/networker_test/domain/store/Product.java
- src/main/java/com/example/networker_test/dto/order/orderinfo/OrderInfoDTO.java
- src/main/java/com/example/networker_test/dto/order/request/OrderData.java
- src/main/java/com/example/networker_test/dto/user/reponese/UserResponse.java
- src/main/java/com/example/networker_test/repository/order/CartItemsRepository.java
- src/main/java/com/example/networker_test/repository/order/OrderInfoRepository.java
- src/main/java/com/example/networker_test/repository/order/PaymentInfoRepository.java
- src/main/java/com/example/networker_test/repository/store/ProductRepository.java
- src/main/java/com/example/networker_test/service/order/OrderService.java
- src/main/java/com/example/networker_test/service/store/ProductService.java
- src/main/resources/application.yml
문의를 위한 이메일 설정, 패키지 오타 수정, 안 쓰는 코드 삭제
> 코드정리 및 앱 비밀번호 설정

- src/main/resources/static/src/js/company.js
- src/main/resources/static/views/review.html
> #171 기업리뷰 페이지 수정

- src/main/resources/static/src/js/post.js
- src/main/resources/static/src/js/review.js
- src/main/resources/static/views/review.html
- #177
- 검색기능 js 코드로 구현했고, 기존 company 페이지와 같은 js 파일을 사용하고 있던 걸 review.js 파일을 생성하여 분리했습니다.
> #177 기업리뷰 검색기능

- src/main/java/com/example/networker_test/domain/comment/CommentLaw.java
- src/main/resources/application.yml
entity 수정(DB수정)
이전 커밋 법률지원 접속 불가능 이슈 해결
> #186 entity 수정

- src/main/resources/static/src/css/inquire.css
- src/main/resources/static/src/css/network.css
- src/main/resources/static/src/js/inquire.js
- src/main/resources/static/src/js/orderinfo.js
- src/main/resources/static/views/inquire.html
- #190 
- #191 홈 화면 스타일 수정
- 결제내역 정보 웹서버 요청 종류를 GET이 아닌 로그인 되어있는 유저의 아이디가 담긴 POST로 변경
> #190, #191, 결제내역 post 요청으로 변경

- src/main/resources/static/src/js/orderinfo.js
- src/main/resources/static/views/orderinfo.html
> #98 백엔드 요청 관련 오류 해결

- src/main/resources/static/src/js/orderinfo.js
> #98 출력되는 금액과 시간 소숫점 이하 수 제거

- src/main/java/com/example/networker_test/controller/review/ReviewController.java
- src/main/java/com/example/networker_test/domain/review/Company.java
- src/main/java/com/example/networker_test/domain/review/Review.java
- src/main/java/com/example/networker_test/repository/review/ReviewRepository.java
- src/main/java/com/example/networker_test/service/review/ReviewService.java
> 기업리뷰 관련 백엔드 디렉토리 및 파일 생성

- src/main/resources/static/src/css/orderdetails.css
- src/main/resources/static/src/js/orderdetails.js
- src/main/resources/static/src/js/orderinfo.js
- src/main/resources/static/views/orderdetails.html
> #207 주문/결제 상세 내역

- src/main/resources/static/src/js/createpost.js
> #209 돌아가기 버튼 이벤트 연결 코드 수정

- src/main/resources/static/src/js/orderdetails.js
- src/main/resources/static/src/js/orderinfo.js
> #212 디버깅용 코드 추가

- src/main/resources/static/src/css/orderdetails.css
- src/main/resources/static/src/js/orderdetails.js
- src/main/resources/static/src/js/orderinfo.js
- src/main/resources/static/views/orderdetails.html
- #212 프론트 코드 문제 해결 후 totalAmount 속성명을 finalAmount로 수정
> #212 웹서버에서 응답받은 데이터 처리 코드 수정

- src/main/java/com/example/networker_test/dto/order/orderResponse/OrderDetailsResponse.java
- src/main/java/com/example/networker_test/dto/order/orderResponse/OrderResponse.java
- src/main/java/com/example/networker_test/service/order/OrderService.java
> #207 구매/결제 내역

- src/main/resources/static/src/js/fetchTitles.js
- src/main/resources/static/views/order.html
> #222 오류 해결

- src/main/resources/static/src/css/shared.css
- src/main/resources/static/views/company1.html
- src/main/resources/static/views/company2.html
- src/main/resources/static/views/company3.html
- src/main/resources/static/views/company4.html
- src/main/resources/static/views/company5.html
- src/main/resources/static/views/company6.html
- src/main/resources/static/views/createpost_law.html
- src/main/resources/static/views/inquire.html
- src/main/resources/static/views/lawsupport.html
- src/main/resources/static/views/login.html
- src/main/resources/static/views/modifypost.html
- src/main/resources/static/views/modifypost_law.html
- src/main/resources/static/views/news.html
- src/main/resources/static/views/nicknamesetting.html
- src/main/resources/static/views/order.html
- src/main/resources/static/views/orderdetails.html
- src/main/resources/static/views/orderinfo.html
- src/main/resources/static/views/passwordchange.html
- src/main/resources/static/views/post.html
- src/main/resources/static/views/post_law.html
- src/main/resources/static/views/productdetail.html
- src/main/resources/static/views/profile.html
- src/main/resources/static/views/review.html
- src/main/resources/static/views/signup.html
- src/main/resources/static/views/store.html
- src/main/resources/static/views/write_review.html
:root {
--text-color: #000;
--background-color: #f9f9f9;
}
:root.dark-mode {
--text-color: #000;  >>> #fff에서 수정했습니다
--background-color: #2b2b2b;
}
> #224 다크모드 텍스트 컬러 수정

- src/main/resources/static/src/js/news.js
- #226 
- 데이터 요청을 처리하는 백엔드 코드는 이미 구현이 되어있어 프론트엔드 코드만 수정함
> #226 정보 DB 연결

- src/main/resources/static/src/css/board.css
- src/main/resources/static/src/css/review_page.css
- src/main/resources/static/src/css/shared.css
- src/main/resources/static/views/company1.html
- src/main/resources/static/views/company2.html
- src/main/resources/static/views/company3.html
- src/main/resources/static/views/post.html
게시판 다크 모드 배경색,글씨 색
리뷰 게시판 배경색 수정했습니다
> #228 다크 모드 글씨 수정

- src/main/resources/static/src/css/cart.css
- src/main/resources/static/src/css/deleteaccount.css
- src/main/resources/static/src/css/emailchange.css
- src/main/resources/static/src/css/inquire.css
- src/main/resources/static/src/css/login.css
- src/main/resources/static/src/css/nicknamesetting.css
- src/main/resources/static/src/css/orderdetails.css
- src/main/resources/static/src/css/orderinfo.css
- src/main/resources/static/src/css/passwordchange.css
- src/main/resources/static/src/css/productdetail.css
- src/main/resources/static/src/css/profile.css
- src/main/resources/static/src/css/shared.css
- src/main/resources/static/src/css/signup.css
- src/main/resources/static/src/css/store.css
- src/main/resources/static/views/deleteaccount.html
- src/main/resources/static/views/emailchange.html
- src/main/resources/static/views/inquire.html
> #196 다크모드 스타일 수정

- src/main/resources/static/src/css/review.css
- src/main/resources/static/views/networker.html
- src/main/resources/static/views/review.html
기업 리뷰 타이틀 넣고 
홈 화면 게시판 2개 주석 처리했습니다
> #231 기업 리뷰 타이틀 넣기, 홈 화면 게시판 2개 제거

- src/main/resources/static/views/company4.html
- src/main/resources/static/views/write_review.html
- 로컬스토리지 이용해서 기업리뷰 생성 및 조회
- company4.html 스타일 미적용 임시 수정
> 로컬스토리지 이용해서 기업리뷰 생성 조회

- src/main/java/com/example/networker_test/controller/post/PostController.java
- src/main/java/com/example/networker_test/controller/post/PostLawController.java
- src/main/resources/application.yml
- src/main/resources/static/src/js/createpost.js
- src/main/resources/static/src/js/createpost_law.js
- src/main/resources/static/views/createpost_law.html
- src/main/resources/static/views/modifypost_law.html
- src/main/resources/static/views/post_law.html
게시판 수정 및 글쓰기 기능 복구
(사진은 업로드는 되지만, url 설정이 이상함)
> #234 게시판 수정 및 글쓰기 기능 복구

- src/main/resources/static/src/js/createpost.js
- src/main/resources/static/src/js/createpost2.js
> #239 글쓰기 오류 관련 수정

- src/main/resources/static/src/css/post.css
- src/main/resources/static/views/post_law.html
- #196 
- post 다크모드 버튼, 법률지원 port 다크모드 적용되도록 오타 수정
> 다크모드 버그 수정

- src/main/resources/static/src/css/board.css
> #258 게시판 테이블 폭 고정

- src/main/java/com/example/networker_test/controller/post/TranslateController.java
- src/main/java/com/example/networker_test/controller/post/TranslationService.java
- src/main/resources/application.yml
- src/main/resources/static/src/js/translate.js
- src/main/resources/static/src/js/translateapi.js
- src/main/resources/static/views/post.html
> #260 자유게시판 content 번역 api
